[tox]
minversion = 3.18.0
envlist = py3,pep8

[testenv]
usedevelop = True
allowlist_externals = rm
setenv =
  VIRTUAL_ENV={envdir}
  PYTHONWARNINGS=default::DeprecationWarning
  OS_STDOUT_CAPTURE=1
  OS_STDERR_CAPTURE=1
  OS_TEST_TIMEOUT=60
  PYTHONDONTWRITEBYTECODE=1
passenv =
  # LOCALE_ARCHIVE is needed when not using python from the system package
  # manager (e.g. when installed with nix) to ensure the locale-archive is
  # available to the tests. specifically this is needed by sphinx to build
  # the docs.
  LOCALE_ARCHIVE
  OS_DEBUG
  # NOTE(sean-k-mooney) optimization is enabled by default and when enabled
  # asserts are complied out. Disable optimization to allow asserts in
  # cyborgclient to fire in unit and functional tests. This can be useful for
  # debugging issue with fixtures and mocks.
  PYTHONOPTIMIZE
deps =
  -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/2025.1}
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
commands = stestr run {posargs}

[testenv:pep8]
commands = flake8 {posargs}

[testenv:venv]
commands = {posargs}

[testenv:cover]
setenv =
  VIRTUAL_ENV={envdir}
  PYTHON=coverage run --source cyborgclient --parallel-mode
commands =
  stestr run {posargs}
  coverage combine
  coverage html -d cover
  coverage xml -o cover/coverage.xml

# Note(chandankumar): pbr===6.1.1 needs pkg_resources, is available in setuptools<82.0.0
[testenv:docs]
deps =
  -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/2025.1}
  -r{toxinidir}/doc/requirements.txt
  setuptools<82.0.0
commands = sphinx-build -W -b html doc/source doc/build/html

[testenv:releasenotes]
deps = {[testenv:docs]deps}
commands =
  sphinx-build -a -E -W -d releasenotes/build/doctrees -b html releasenotes/source releasenotes/build/html

[testenv:debug]
commands = oslo_debug_helper {posargs}

[flake8]
# E123, E125 skipped as they are invalid PEP-8.
# W504 line break after binary operator
# E402 module level import not at top of file
show-source = True
ignore = E123,E125,W504,E402
builtins = _
exclude=.venv,.git,.tox,dist,doc,*lib/python*,*egg,build
